language: node_js
sudo: required
dist: trusty
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable    
branches:
  except:
  - "/^v\\d/"
install:
  - yarn global add polymer-cli
  - yarn global add bower
  - yarn install
  - bower install
before_script:
  - polymer lint
script:
  - xvfb-run polymer test
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "Lighthouse CI only runs on Pull Requests.";
      exit;
    fi
  - yarn global add firebase-tools
  - yarn add https://github.com/ebidel/lighthouse-ci
  - polymer build
  - firebase deploy --token $FIREBASE_TOKEN --project guide2production-dev
  - node node_modules/lighthouse-ci/runlighthouse.js https://guide2production-dev.firebaseapp.com
before_deploy:
  - if [ $TRAVIS_BRANCH = "develop" ]; then
      polymer build;
      firebase deploy --token $FIREBASE_TOKEN --project guide2production-dev;
    elif [ $TRAVIS_BRANCH = "master" ]; then
      polymer build;
      firebase deploy --token $FIREBASE_TOKEN --project guidetoproductionapp;
    fi

notifications:
  email:
    on_failure: change
    on_success: change