language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "6"
cache:
  yarn: true
branches:
  except:
  - /^v\d/
install:
  - yarn global add bower
  - yarn install
  - bower install
before_script:
  - yarn run lint
  - yarn run lint:eslint
script:
  - xvfb-run yarn run test:integration
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "Lighthouse CI only runs on Pull Requests.";
      exit;
    fi
  - yarn global add firebase-tools
  - yarn add https://github.com/ebidel/lighthouse-ci
  - yarn run build
  - firebase deploy --token $FIREBASE_TOKEN --project guide2production-dev
  - node node_modules/lighthouse-ci/runlighthouse.js https://guide2production-dev.firebaseapp.com
before_deploy:
  - if [ $TRAVIS_BRANCH = "develop" ]; then
      yarn run build;
      firebase deploy --token $FIREBASE_TOKEN --project guide2production-dev;
    elif [ $TRAVIS_BRANCH = "master" ]; then
      yarn run build;
      firebase deploy --token $FIREBASE_TOKEN --project guidetoproductionapp;
    fi

notifications:
  email:
    on_failure: change
    on_success: change